server:
  port: 8082

spring:
  application:
    name: casualty-investigation
  datasource:
    url: jdbc:postgresql://localhost:5432/casualtydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Maroon@54321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: false
      path: /h2-console
