server:
  port: 8084

spring:
  application:
    name: safety-circulars-dms
  datasource:
    url: jdbc:postgresql://localhost:5432/safetycircularsdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Maroon@54321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: false
      path: /h2-console
